config/routes.rb
# frozen_string_literal: true

require "patterns"

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  resources :categories, only: %i[show]
  resources :projects, only: %i[show], constraints: { id: Patterns::ROUTE_PATTERN }
  resource  :search, only: %i[show]
  resources :blog, only: %i[index show], constraints: { id: /[^\.]+/ }

  root "welcome#home"
end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    title= title
    = csrf_meta_tags

    meta charset="utf-8"/
    meta name="viewport" content="width=device-width, initial-scale=1"/
    meta http-equiv="x-ua-compatible" content="ie=edge"/
    meta name="description" content=description

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    link href="/apple-touch-icon.png" rel="apple-touch-icon" sizes="180x180" /
    link href="/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png" /
    link href="/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png" /
    link href="/favicon.ico" rel="shortcut icon"
    link href="/manifest.json" rel="manifest" /
    link color="#dd2b2b" href="/safari-pinned-tab.svg" rel="mask-icon" /
    meta content=site_name name="apple-mobile-web-app-title" /
    meta content=site_name name="application-name" /
    meta content="#ffffff" name="theme-color" /

    meta content="website" property="og:type" /
    meta content=request.original_url property="og:url" /
    meta content=title property="og:title" /
    meta content=image_url("logo/box-with-padding.png") property="og:image" /
    meta content=description property="og:description" /
    meta content=site_name property="og:site_name" /
    meta content="en_US" property="og:locale" /

    meta content="summary" name="twitter:card" /
    meta content="@rubytoolbox" name="twitter:site" /
    meta content="@thedeadserious" name="twitter:creator" /
    meta content=request.original_url name="twitter:url" /
    meta content=title name="twitter:title" /
    meta content=description name="twitter:description" /
    meta content=image_url("logo/box-with-padding.png") name="twitter:image" /

    = auto_discovery_link_tag :rss, blog_index_url(format: :rss)

  body
    header.section: .container
      nav.level.is-mobile
        .level-left
          .level-item
            = link_to "/", title: title(default: true) do
              = image_tag "logo/regular.svg", alt: title(default: true)
        .level-right
          - unless controller_name == "searches"
            .is-hidden-tablet
              = link_to search_path, class: "button is-white is-large" do
                span.icon: i.fa.fa-search
          .search-form.level-item.is-hidden-mobile
            = form_tag search_path, method: :get do
              .field.has-addons.has-addons-centered
                .control
                  input.input placeholder="Search" type="text" name="q" value=@query
                .control
                  button.button type="submit"
                    span.icon: i.fa.fa-search
                    span Search


    section.main= yield

    footer.footer
      .container
        .columns
          .column.navigation
            .heading Navigation
            ul
              li= link_to "Home", root_path
              li= link_to "News", blog_index_path
              li= link_to "Search", search_path

          .column.who
            .heading Who
            .content
              markdown:
                The Ruby Toolbox is brought to you from Hamburg since 2009 by [Christoph Olszowka](http://www.olszowka.de)

                If you want to personally say hi or complain, you can do so via mail to me at christoph (at) ruby-toolbox (dot) com

                You can also find me on Twitter as [@thedeadserious](https://twitter.com/thedeadserious)
                and on [Github](https://github.com/colszowka)

          .column.contributing
            .heading Contributing
            .content
              markdown:
                You can find the source code for this site [on github](https://github.com/rubytoolbox/rubytoolbox).

                The categorization of gems is handled via the [catalog][catalog], which you can also find [on
                Github][catalog]

                [catalog]: https://github.com/rubytoolbox/catalog

                Contributions welcome <span class="icon has-text-danger"><i class="fa fa-heart"></i></span>!

          .column.links
            .heading Links
            ul
              li: a href="https://github.com/rubytoolbox/rubytoolbox/blob/master/CODE_OF_CONDUCT.md"
                span.icon: i.fa.fa-users
                span Code of Conduct
              li: a href=feed_url
                span.icon: i.fa.fa-rss-square
                span RSS Feed
              li: a href="https://github.com/rubytoolbox/rubytoolbox/projects/1"
                span.icon: i.fa.fa-github
                span Project Planning Board
              li: a href="https://github.com/rubytoolbox/rubytoolbox"
                span.icon: i.fa.fa-github
                span rubytoolbox/rubytoolbox
              li: a href="https://github.com/rubytoolbox/catalog"
                span.icon: i.fa.fa-github
                span rubytoolbox/catalog

        hr

        .columns
          .column
            h4.subtitle.is-5.has-text-centered Sponsors
        .columns.sponsors
          .column
            .heading Development funded by
            a href="https://rubytogether.org/"
              = image_tag "sponsors/rubytogether-white.svg", style: "height: 95px"
          .column
            .heading Hosted on
            a href="https://heroku.com/"
              = image_tag "sponsors/heroku.svg", style: "height: 55px; margin-top: 20px"
          .column
            .heading Monitored with
            a href="https://appsignal.com/"
              = image_tag "sponsors/appsignal-logo-horizontal.svg", style: "height: 35px; margin-top: 28px"
        .columns: .column.has-text-centered: strong.heading Thank You!